# Generated by Django 4.2.4 on 2023-08-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_plan_type', models.CharField(max_length=100)),
                ('fee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=5)),
                ('age', models.IntegerField()),
                ('purpose', models.CharField(max_length=50)),
                ('membership_plan', models.CharField(max_length=100)),
                ('total_fees', models.IntegerField()),
                ('fees_paid', models.IntegerField()),
                ('fees_remaining', models.IntegerField()),
                ('last_paid_date', models.DateField()),
                ('fees_due_date', models.DateField()),
                ('date_of_join', models.DateField()),
            ],
        ),
    ]
