# Generated by Django 4.2.4 on 2023-08-28 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0002_member_updated_plan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='updated_plan_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 28, 15, 7, 8, 952964, tzinfo=datetime.timezone.utc)),
        ),
    ]
