# Generated by Django 4.2.4 on 2023-08-30 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0003_alter_member_updated_plan_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='pt_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='updated_plan_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 30, 13, 33, 23, 672436, tzinfo=datetime.timezone.utc)),
        ),
    ]
