# Generated by Django 4.2.4 on 2023-08-30 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0005_trainer_member_personal_trainer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='date_of_join',
            field=models.DateField(default=datetime.datetime(2023, 8, 30, 16, 4, 38, 494963, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='updated_plan_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 30, 16, 4, 38, 494963, tzinfo=datetime.timezone.utc)),
        ),
    ]
