# Generated by Django 4.2.4 on 2023-08-31 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0006_trainer_date_of_join_alter_member_updated_plan_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='batch_time',
            field=models.CharField(default='Morning', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='personal_trainer_name',
            field=models.CharField(default='Not Applicable', max_length=50),
        ),
        migrations.AddField(
            model_name='trainer',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2023, 8, 31, 6, 27, 52, 936676, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='trainer',
            name='gender',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='fee',
            name='fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='updated_plan_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 31, 6, 27, 52, 935675, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='date_of_join',
            field=models.DateField(default=datetime.datetime(2023, 8, 31, 6, 27, 52, 936676, tzinfo=datetime.timezone.utc)),
        ),
    ]
