# Generated by Django 4.2.4 on 2023-09-08 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0021_alter_member_age_alter_member_updated_plan_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='batch_time',
            field=models.CharField(default='Morning', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='date_of_join',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='fees_due_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='fees_paid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='fees_remaining',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_paid_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_plan',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='personal_trainer',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='personal_trainer_name',
            field=models.CharField(default='Not Applicable', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='purpose',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='total_fees',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='updated_plan_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 8, 13, 15, 31, 534874, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2023, 9, 8, 13, 15, 31, 534874, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='date_of_join',
            field=models.DateField(default=datetime.datetime(2023, 9, 8, 13, 15, 31, 534874, tzinfo=datetime.timezone.utc)),
        ),
    ]
