# Generated by Django 4.2.4 on 2023-09-08 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0022_alter_member_batch_time_alter_member_date_of_join_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='batch_time',
            field=models.CharField(default='Morning', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='date_of_join',
            field=models.DateField(default='0'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='member',
            name='fees_due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='fees_paid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='fees_remaining',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='member',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_paid_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_plan',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='personal_trainer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='personal_trainer_name',
            field=models.CharField(default='Not Applicable', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='purpose',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='total_fees',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='updated_plan_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 8, 13, 17, 40, 741968, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='weight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2023, 9, 8, 13, 17, 40, 741968, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='date_of_join',
            field=models.DateField(default=datetime.datetime(2023, 9, 8, 13, 17, 40, 741968, tzinfo=datetime.timezone.utc)),
        ),
    ]
