# Generated by Django 4.2.4 on 2023-09-09 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0023_alter_member_address_alter_member_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='updated_plan_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 9, 13, 40, 19, 658921, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2023, 9, 9, 13, 40, 19, 659920, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='date_of_join',
            field=models.DateField(default=datetime.datetime(2023, 9, 9, 13, 40, 19, 659920, tzinfo=datetime.timezone.utc)),
        ),
    ]
